# Generated by Django 5.1.2 on 2024-12-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_friend_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
