# Generated by Django 5.1.2 on 2024-12-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_conversation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='creator',
        ),
    ]
