# Generated by Django 5.1.2 on 2024-12-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
