# Generated by Django 5.1.2 on 2024-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_message_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seens',
            field=models.ManyToManyField(related_name='seens', to='main.user'),
        ),
    ]
