# Generated by Django 5.1.2 on 2024-12-18 07:36

import main.models.message
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_message_seens'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.message.upload_image),
        ),
    ]
