# Generated by Django 5.1.2 on 2024-12-18 08:16

import django.db.models.deletion
import main.models.message
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_message_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to=main.models.message.upload_image)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.message')),
            ],
        ),
    ]
