# Generated by Django 5.1.2 on 2024-12-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_message_image_messageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageimage',
            old_name='url',
            new_name='image',
        ),
    ]
