# Generated by Django 5.1.2 on 2024-12-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_url_messageimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageimage',
            old_name='image',
            new_name='url',
        ),
    ]
