# Generated by Django 5.1.2 on 2024-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_image_messageimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
