# Generated by Django 5.1.2 on 2024-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_message_isedited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isDeleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='isEdited',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
