# Generated by Django 5.1.2 on 2024-12-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_reaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='MessageReaction',
        ),
    ]
