# Generated by Django 5.1.2 on 2024-12-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_reaction_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isReacted',
            field=models.BooleanField(default=False),
        ),
    ]
