# Generated by Django 5.1.2 on 2024-12-18 12:12

import main.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_message_isreacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.user.upload_avatar),
        ),
    ]
