# Generated by Django 5.1.2 on 2024-12-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isActve',
            field=models.BooleanField(default=False),
        ),
    ]
