# Generated by Django 5.1.2 on 2024-12-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_user_isactve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isActve',
            new_name='isOnline',
        ),
    ]
