# Generated by Django 5.1.2 on 2024-12-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_isactve_user_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastMessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_lastmessage', to='main.message'),
        ),
    ]
